name: Auto Release on PR Merge

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:
    inputs:
      pr_title:
        description: 'PR Title (for testing - include version like [v1.2.3])'
        required: true
        type: string
        default: 'feat: Test release [v1.0.0]'

jobs:
  create-release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from PR
        id: extract-version
        run: |
          # Extract from PR title (e.g. "feat: Add new feature [v1.2.3]")
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            PR_TITLE="${{ github.event.inputs.pr_title }}"
            echo "Manual trigger - using provided PR title: $PR_TITLE"
          else
            PR_TITLE="${{ github.event.pull_request.title }}"
            echo "PR Title: $PR_TITLE"
          fi
          
          VERSION=$(echo "$PR_TITLE" | grep -oP '\[v\K[0-9]+\.[0-9]+\.[0-9]+(?=\])')
          
          if [[ -z "$VERSION" ]]; then
            echo "No version found in PR title '$PR_TITLE'. Expected format: [v1.2.3]"
            echo "Skipping release creation."
            exit 1
          fi
          
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check-tag
        run: |
          if git rev-parse "v${{ steps.extract-version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.extract-version.outputs.version }} already exists. Skipping release."
            exit 1
          fi

      - name: Configure git with PR author
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action (Manual Trigger)"
          else
            git config --local user.email "${{ github.event.pull_request.user.email || format('{0}@users.noreply.github.com', github.event.pull_request.user.login) }}"
            git config --local user.name "${{ github.event.pull_request.user.login }}"
          fi

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ steps.extract-version.outputs.tag }}" -m "Release ${{ steps.extract-version.outputs.tag }}"
          git push origin "${{ steps.extract-version.outputs.tag }}"

      - name: Create GitHub Release
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ steps.extract-version.outputs.tag }}',
              name: 'Release ${{ steps.extract-version.outputs.tag }}',
              draft: false,
              prerelease: false,
              generate_release_notes: true  // This ensures GitHub adds any additional auto-generation
            });