name: CI

on:
  workflow_call: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'

      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
        env:
          COVERAGE_OUTPUT: coverage.cobertura.xml
      