name: Build and Release Package

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use provided version
        id: get_version
        run: |
            echo "Releasing version: ${{ inputs.version }}"
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT